### ISSUE TITLE
OBS studio Compatibility

### ISSUE THREAD

**Issue by ItsFoxCrafter** [VxKex/VxKex#2]
Hi, I just wanted to say is it possible for you to make it that OBS studio works using VxKex

**Comment by vxiiduu1** [comment]
Hi, what's issue with the application? It doesn't launch or maybe some functions are broken?

**Comment by ItsFoxCrafter** [comment]
> Hi, what's issue with the application? It doesn't launch or maybe some functions are broken?

Its Not Supported for windows7

**Comment by vxiiduu1** [comment]
Did you enable vxkex to obs studio .exe after installation?
