### ISSUE TITLE
gitgud.io or Gitlab backup?

### ISSUE THREAD

**Issue by metapea** [VxKex/VxKex#3]
Just in case, so it doesn't get taken down again. 
Can you reupload the source code to gitgud.io and mirror issues to there, so that we don't lose anything.
And were any of the issues or zips for [VxKex](https://github.com/VxKex/VxKex) logs saved?

**Comment by vxiiduu1** [comment]
I will reupload it to gitlab very soon. Sadly i dont have any backup of issues or anything except latest source code + release .exe.

**Comment by win98se** [comment]
Fortunately, someone mirrored the old Git repo (along with full history, but without issues or releases) at https://github.com/PopuriAO29/VxKex.
