### ISSUE TITLE
Current main bugs: scaling bug and uninstaller bug

### ISSUE THREAD

**Issue by YuZhouRen86** [VxKex/VxKex#4]
Hello!
I am very happy to see the project is still fine, and thank vxiiduu very much.
The current VxKex still has scaling bug on high resolution screens, it causes tiny interfaces of many programs under VxKex (e.g. VSCode). And another problem is the users cannot uninstall it when they upgrade from Windows 7 to 8.x/10/11, they cannot even open the properties of EXEs.

**Comment by vxiiduu1** [comment]
Hello, 
I will add high resolution scalling bug fix to 2.0 todo,
In my opinon, upgrading problem isnt something that is worth fixing, just uninstall it while being on windows 7. 
Have a great day!
