### ISSUE TITLE
How VxKex works

### ISSUE THREAD

**Issue by DfsDirect327** [VxKex/VxKex#5]
Denuvo Anti-Tampering is included in some PC games. It prevents the users from pirating by blocking attempts to modify the game executable file and maybe also the game's memory space. As far as I know copying DLLs to the game folder is okay and doesn't count as an attempt to illegally tamper or pirate. 

Therefore it is of big interest to know how VxKex works. Could anyone used to the project please explain this? I want to be careful since you can be banned from Steam or the game if you violate the anti-tampering rules.

**Comment by vxiiduu1** [comment]
You can download VxKex source code [here](https://github.com/VxKex/VxKex/releases/download/release/SourceCode.7z) and check how it works yourself, but shortly it loads dll into program with vxkex enabled. VxKex shouldn't trigger any anti-tampering but i can't promise it 100%.
